# Generated by Django 4.1.1 on 2022-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_Shows_app', '0002_alter_show_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='desc',
            new_name='description',
        ),
    ]
